name: frenzykey  # <-- Esto forzará el nombre del proyecto

services:
  db:
    image: postgres:15-alpine
    container_name: frenzykey_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: frenzy_password
      POSTGRES_DB: frenzykey_db
    volumes:
      - frenzy_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: frenzykey_backend
    environment:
      - DATABASE_URL=postgresql://admin:frenzy_password@db:5432/frenzykey_db
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frenzykey_frontend
    ports:
      - "8000:80"  # <--- Asegúrate de que diga esto
    #volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  frenzy_db_data: